### ISSUE TITLE
Unable to start debugging

### ISSUE THREAD

**Issue by pizza** [steobrien/light-up-running-code#1]
Hey 👋 I'd love to try this locally, but I am having trouble with the 3rd step in the README.

![image](https://user-images.githubusercontent.com/1456331/82320506-544d8a00-99cb-11ea-8193-d0b79cee53c5.png)

When I click on `Start debugging`, I get the following error at the bottom right, followed by the error window at the top saying `The specified task cannot be tracked`.

![image](https://user-images.githubusercontent.com/1456331/82320458-3aac4280-99cb-11ea-95c1-483438ebc12f.png)

Not sure if I'm doing something wrong or if I missed a pre-requesite.

**Comment by steobrien** [comment]
Couldn't reproduce this exact error, but realized I neglected to specify installing the extension's node modules and building it. Sorry!

Can you try the [steps](https://github.com/steobrien/light-up-running-code#run-this-yourself-locally) one more time, this time running the build script with `bin/build` before pressing play in VS Code?

Thanks for checking it out.

**Comment by pizza** [comment]
That did it!

I had run `npm install` inside the extension folder before opening the issue, but I didn't know about `npm run watch`.

Thanks Stephen!
